apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: app-of-apps
  source:
    path: k8s/apps
    repoURL: https://github.com/cedsbe/home-infra
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
