http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h

auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto

dns:
  # General settings
  bind_hosts:
    - 0.0.0.0
  port: 53
  anonymize_client_ip: false

  # Anti-DNS amplification features
  ratelimit: 500
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true

  # Upstream DNS servers settings
  upstream_dns:
    - 10.96.0.11
  upstream_dns_file: ""
  bootstrap_dns:
    - 10.96.0.11
  fallback_dns:
    - 86.54.11.1 # DNS4EU - Protective
    - 9.9.9.9 # Quad9 - Malware Blocking
  upstream_mode: parallel
  fastest_timeout: 1s
  bootstrap_prefer_ipv6: false
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  use_http3_upstreams: false

  # ECS settings
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false

  # Access settings
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128

  # DNS cache settings
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false

  # Other settings
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  upstream_timeout: 10s
  serve_http3: false
  serve_plain_dns: true
  hostsfile_enabled: true

tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false

querylog:
  dir_path: ""
  ignored: []
  interval: 2160h
  size_memory: 1000
  enabled: true
  file_enabled: true

statistics:
  dir_path: ""
  ignored: []
  interval: 24h
  enabled: true

filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2

whitelist_filters: []

user_rules:
  - "@@||sdk.iad-01.braze.com^$important" # Payments?
  - "@@||www.merchant-center-analytics.goog^$important"

dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false

filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites:
    - domain: "*.k8s.ghiot.be"
      answer: 192.168.65.140
    - domain: k8s.ghiot.be
      answer: 192.168.65.140
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true

clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent:
    - safe_search:
        enabled: true
        bing: true
        duckduckgo: true
        ecosia: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids:
          - 4chan
          - onlyfans
          - peacock_tv
          - plenty_of_fish
          - temu
          - tinder
          - betway
          - mail_ru
          - ok
          - viber
          - wechat
      name: Kids
      ids:
        - 192.168.75.0/24
      tags:
        - user_child
      upstreams:
        - 86.54.11.11 # DNS4EU - Protective + Child Protection + Ad Blocking
      uid: 019418f8-a0ff-7079-a3ae-1d85f8a6f129
      upstreams_cache_size: 0
      upstreams_cache_enabled: false
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: true
      safebrowsing_enabled: true
      use_global_blocked_services: false
      ignore_querylog: false
      ignore_statistics: false

log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false

os:
  group: ""
  user: ""
  rlimit_nofile: 0

schema_version: 28
