---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-github-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgCCOFeBg8gPamoY4bQ3QjO9eTi44Wl2bBIPLoO9ZeqfCtraQ3o5zAv8pBIQupeA2q+H87h3ReUWVRw4L+wg2/k2TPH7ygDpcRp1PBzHq/8Y5hFRGJqK3GeXfGopt6T5xc94y1xFwPqaOvE1/3ZjweDGxREnYL67zVK1VPTaqerzvGbDxP+L3ZyH4nk7ubbooipzUlUcvm6rkjoXercThZT9UguzWeppqe+vSLCPS/5hIrNv5AB1NOlsusGbBBwgP6lEyElkCMO+73n8LLasK9MDWzgalAkOqONwmIBKRnd6QZ+MXLtEv5Ky9rZk5PjmGDl3Kpx+2i4LmdjBzkx0FMIabg4UZyRaRaw1dEJDGIlC4w8YXuiXPvtfCRBBV4FdJyS1OpHKyu+SXbHsDZm6VRKLw8Lrpjhps/hTsaDJagldGjXVN/4jc4pGFwI3EyZ8kTcTH9ZI2hhjS0lUpyDZafr+neTdNUPlhIqCOOZ3QLkQPpmnrGmajLN2TR3R+A2iyyUtoxvL4ZmUULUVgL3oCViokqu59YkxjnWy/+O7xPGhZ6W89cMPdS3EN9/jJI6qeyXTT0gv3+EdO/c8xN+livGnWTBU10uq3M9x3EJAxKA9Vb90PxNhh5iGXf2DqtAzSnMVK0yoyMZ7OrTXsAsi3mUF2PZjlR9jz3xKjzCfLgjbUlVh/tYZcX+tJgMwZUyEmf6kciQMLDooM+iyxn8TtQGjYKBYV29Ws+LTv7CePpxkV3Q/J5/6NAR/dZBoIkngrlL91MwW+AVpQQE1iPEyWEObf4Uahhp0R5HuO3h4DnP9Jol4eaGaLJeUayb1J3c=
  template:
    metadata:
      name: arc-github-secret
      namespace: arc-runners
    type: Opaque
