severity:
  - HIGH
  - CRITICAL
  - MEDIUM

# Allowed registries for container images. Too expensive to host them all locally.
allowed-registries:
  - docker.io
  - ghcr.io
  - registry.k8s.io
  - quay.io
  - gcr.io

# Skip checks for specific advisories if needed
skip-db-update: false
