apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: adguard
  namespace: dns
spec:
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: copy-base-config
          image: busybox
          command:
            [
              "cp",
              "/tmp/AdGuardHome.yaml",
              "/opt/adguardhome/conf/AdGuardHome.yaml",
            ]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            - name: config-folder
              mountPath: /opt/adguardhome/conf
        - name: append-users
          image: busybox
          command:
            [
              "sh",
              "-c",
              "cat /tmp/users.yaml >> /opt/adguardhome/conf/AdGuardHome.yaml",
            ]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: users
              mountPath: /tmp/users.yaml
              subPath: users.yaml
            - name: config-folder
              mountPath: /opt/adguardhome/conf
      containers:
        - name: adguard
          image: docker.io/adguard/adguardhome:v0.107.73@sha256:7fbf01d73ecb7a32d2d9e6cef8bf88e64bd787889ca80a1e8bce30cd4c084442 # renovate: datasource=docker depName=docker.io/adguard/adguardhome packageName=docker.io/adguard/adguardhome versioning=docker registryUrl=https://index.docker.io
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          # capabilities:
          #   drop: [ "ALL" ]
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dchp
              containerPort: 67
              protocol: UDP
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config-folder
              mountPath: /opt/adguardhome/conf
            - name: work-folder
              mountPath: /opt/adguardhome/work
      volumes:
        - name: config
          configMap:
            name: adguard-config
        - name: users
          secret:
            secretName: adguard-users-secrets
        - name: config-folder
          emptyDir: {}
        - name: work-folder
          emptyDir: {}
