# YAML Lint configuration for home-infra
extends: default

rules:
  # Line length
  line-length:
    max: 150
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Document start/end
  document-start:
    present: false

  document-end:
    present: false

  # Truthy values (allow yes/no, on/off, etc.)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

# Ignore certain files
# ignore: |
#   .github/workflows/
#   k8s/
#   .pre-commit-config.yaml
