# https://taskfile.dev

version: "3"

vars:
  CILIUM_VERSION: v1.16.5

env:
  KUBECONFIG: terraform/kubernetes/output/kube-config.yaml
  TALOSCONFIG: terraform/kubernetes/output/talos-config.yaml

tasks:
  bootstrap_cilium_config:
    cmds:
      - |
        helm template \
          cilium \
          cilium/cilium \
          --version={{.CILIUM_VERSION}} \
          --namespace kube-system \
          --set kubeProxyReplacement=true \
          --values k8s/infra/network/cilium/values_bootstrap.yaml > terraform/kubernetes/modules/talos/talos-inline-manifests/sensitive_cilium_helm_template.yaml
    sources:
      - k8s/infra/network/cilium/values_bootstrap.yaml
    generates:
      - terraform/kubernetes/modules/talos/talos-inline-manifests/sensitive_cilium_helm_template.yaml

  ####################
  # Tools
  ####################

  all_tools_install:
    desc: "Install all tools"
    deps:
      - argocd_cli_install
      - cilium_install
      - kubeseal_install
      - kustomize_install
      - talosctl_install

  argocd_cli_install:
    desc: "Install ArgoCD CLI"
    cmds:
      - brew install argocd

  cilium_cli_install:
    desc: "Install Cilium CLI"
    cmds:
      - bash task_scripts/cilium_cli_install.sh

  cilium_hubble_install:
    desc: "Install Cilium Hubble"
    cmds:
      - bash task_scripts/cilium_hubble_install.sh

  cilium_install:
    desc: "Install Cilium and Hubble"
    deps:
      - cilium_cli_install
      - cilium_hubble_install

  k9s_install:
    desc: "Install K9s"
    cmds:
      - brew install k9s

  kubeseal_install:
    desc: "Install kubeseal"
    cmds:
      - brew install derailed/k9s/k9s

  kustomize_install:
    desc: "Install Kustomize"
    cmds:
      - brew install kustomize

  talosctl_install:
    desc: "Install talosctl"
    cmds:
      - brew install siderolabs/tap/talosctl

  ####################
  # Infrastructure
  ####################

  # TODO: Add the backend configuration
  bootstrap_terraform_init:
    desc: "Initialize Terraform"
    cmds:
      - terraform init
    deps:
      - bootstrap_cilium_config
    dir: terraform/kubernetes

  bootstrap_terraform_talos:
    desc: "Bootstrap the Talos Kubernetes cluster"
    cmds:
      - terraform apply -target module.talos -auto-approve
    deps:
      - bootstrap_terraform_init
    dir: terraform/kubernetes

  bootstrap_terraform_csi:
    desc: "Bootstrap the Proxmox CSI plugin"
    cmds:
      - terraform apply -target module.csi -auto-approve
    deps:
      - bootstrap_terraform_talos
    dir: terraform/kubernetes

  cilium_test:
    desc: "Run Cilium tests"
    cmds:
      - kubectl label namespace cilium-test-1 pod-security.kubernetes.io/enforce=privileged # The test requires privileged pods
      - cilium hubble port-forward&
      - cilium connectivity test
