apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-cluster-issuer
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.65.140
  listeners:
    - protocol: HTTP
      port: 80
      name: http-gateway
      hostname: "*.k8s.ghiot.be"
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTP
      port: 80
      name: http-domain-gateway
      hostname: k8s.ghiot.be
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.k8s.ghiot.be"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - name: wildcard-k8s-ghiot-be-tls
            kind: Secret
            group: ""

    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: k8s.ghiot.be
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - name: domain-k8s-ghiot-be-tls
            kind: Secret
            group: ""
