apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - network-policies.yaml
  - pvc.yaml
  - secret-claim.yaml
  - svc.yaml
  - svc-plex.yaml
  - http-route.yaml
  - deployment.yaml
