---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-claim
  namespace: plex
spec:
  encryptedData:
    PLEX_CLAIM_TOKEN: AgClX7DAonotgQ7dxjVA0hZwjnJq7CFhc41KNo2/THcC0w7z2OogztkYmTU91IDEQm0yMLxME8V7XxRSM95vy3m7xkSPhBTQ26/aM+fJbrOuE+Kz6/5ohE1lyoh/VFM5ePXwhkHtIO4JdgA42NsA0K9i4RYXjlqJQzr0yfwG/Kb6Kz/jHI38vWzHK0okgOMCcaDocAgRD1W+8g4VujFXkRoNN4Nk9YVqRfRhnkFRQGUUzIXifuht4rM2gavglixm+naUXgkwbNuAH/Fr9PvdQ/P7LD+xvjHm0PjxfLTUybmyZlTl3Gqch0Q/gfqQ5nzybaU1P/VgEKwAcHhHkUBsy6V4SVSV9b9LB7eWBEG7Ujo7bR49bIcLF2x/6B6JWkrIUeAsw+O7v0r2Wv1hW4vMOBimdVH0ojdmxZcaQo48j+qP5lmpJQ5qNcy42aUqjzVZNxzvsQwIOMVUp+KDV7n7QmPj4/T+l+q90tAtAVsFDh8KJuOtzgiScRttt6ZcTnOmRnvK8R/3Fu5uwkohouhuSIxqsv3URqnDnW2Zbap3mJOrpsdnh7rpHQIgtAnrilN2SfSaZx5Ogtqijx2RewqkpCPI+d5bbOhJJYxVv62uVybIvfdHjYKfn0gXjWF7CCbKfRDOcCKf1DKYe0KbfE+cwamX4mUoTFweAzR2ldZ+pOzdFmHghSmv5/4oNvGjcEVFq+lRUIgA1Z1wWiRlJRjv9n/WPApPSLajbe7AAA==
  template:
    metadata:
      name: plex-claim
      namespace: plex
