apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  disableDefaultAdminSecret: true
  config:
    log:
      mode: console
    server:
      root_url: https://grafana.k8s.ghiot.be
  version: docker.io/grafana/grafana:13.1.1@sha256:7cb8c64c4d57a57e734073f3cc94620adb24a0acb929bd80ba9f14017e3a975b # renovate: datasource=docker depName=docker.io/grafana/grafana packageName=docker.io/grafana/grafana versioning=regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)(?:-security-(?<build>\d+))?(?:-(?<compatibility>.*))?$ registryUrl=https://index.docker.io
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: admin-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: admin-credentials
