# installCRDs: true
crds:
  enabled: true
  keep: true
extraArgs:
  - "--enable-gateway-api"
  - "--dns01-recursive-nameservers=86.54.11.100:53,9.9.9.9:53" # DNS4EU Unfiltered + Quad9

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
webhook:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
cainjector:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
