apiVersion: v1
kind: Secret
metadata:
  name: argocd-custom-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # echo "q8YBRNKOgZdARIxbGf2w7ik231CSnUNL" | base64
  oidc.pocket-id.client-secret: cThZQlJOS09nWmRBUkl4YkdmMnc3aWsyMzFDU25VTkwK
