githubConfigUrl: https://github.com/cedsbe/home-infra
githubConfigSecret: arc-github-secret

minRunners: 0
maxRunners: 5

controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: "ghcr.io/cedsbe/actions-runner-cedsbe@sha256:530306972196d1e4ff1c60f917dd08708face9606e74f6e42cca8868f4771261"
        command: ["/home/runner/run.sh"]
