githubConfigUrl: https://github.com/cedsbe/home-infra
githubConfigSecret: arc-github-secret

minRunners: 0
maxRunners: 5

controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: "docker pull ghcr.io/cedsbe/actions-runner-cedsbe:latest"
