githubConfigUrl: https://github.com/cedsbe/home-infra
githubConfigSecret: arc-github-secret

minRunners: 0
maxRunners: 5

controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: "ghcr.io/cedsbe/actions-runner-cedsbe:772c10293c9768ecb982cb2502ed8bba4e472d6a"
        command: ["/home/runner/run.sh"]
