apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.17.3
    releaseName: "sealed-secrets-controller"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml
